name       : purple-plugin-pack
version    : 2.8.0
release    : 1
source     :
    - https://sourceforge.net/projects/pidgin/files/purple%20plugin%20pack/2.8.0/purple-plugin-pack-2.8.0.tar.xz : 82ccde9a7251a75b7e03a3f9a929014d8e008c1b6f46e58638f5f476da3e242d
license    :
    -  CC0-1.0
    -  GPL-2.0-or-later
component  : network.im
summary    :
    - Plugin Pack for libpurple and derived IM clients such as Pidgin
description:
    - The Purple Plugin Pack was originally created by Gary Kramlich and Stu Tomlinson as a way to distribute their ever growing lists of simple Pidgin plugins. It has since grown from its origins of about 6 plugins to over 50.
builddeps  :
    - pkgconfig(finch)
    - pkgconfig(gtkspell-2.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(pidgin)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
